#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

clear 
echo -e "                      ${BROWN}######################################${NC}"			
echo -e "		       ${BROWN}#     macOS Theme for Linux mint     #${NC}"
echo -e "		       ${BROWN}#----------------------------------- #${NC}"
echo -e "		       ${BROWN}#  Author   : Robert Grubecki        #${NC}"         
echo -e "		       ${BROWN}#  Email    : robery5384@gmail.com   #${NC}" 
echo -e "		       ${BROWN}######################################${NC}"

#Install required packages
echo -e "${CYAN}Starting  : ${NC}${YELLOW}Attempting to install Required Packages : Curl, Gnome Tweak Tool, GTK Clutter and figlet${NC}"
xterm -e 'sh -c "echo Curl, Gnome Tweak Tool and GTK Clutter will be installed. Please enter your password.; sudo apt update; sudo apt install curl gnome-tweak-tool gir1.2-gtkclutter-1.0 figlet -y"'
echo -e "${GREEN}Finished  : ${NC}${YELLOW}Installing Packages : Curl, Gnome Tweak Tool, GTK Clutter${NC}"

sudo figlet -c "120.0 MB will be downloaded"

echo -e "${CYAN}Starting  : ${NC}${YELLOW}Downloading required files${NC}"
cd ~/Downloads/ 
curl -L -O https://www.dropbox.com/sh/x0xrma1o2as53da/AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0
echo -e "${GREEN}Finished  : ${NC}${YELLOW}Downloading required files${NC}" 
[ ! -d macOS Catalina For Linux Mint 19.3 ] && mkdir -p macOS Catalina For Linux Mint 19.3 
tar xvf AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0 -C AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0 
clear 
cd AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0  
[ ! -d ~/.themes ] && mkdir -p ~/.themes
#[ ! -d ~/Downloads/Apple-Darwin-For-Plymouth/darwin ] && mkdir -p ~/Downloads/Apple-Darwin-For-Plymouth/darwin
[ ! -d ~/.icons ] && mkdir -p ~/.icons
[ ! -d ~/.local/share/fonts ] && mkdir -p ~/.local/share/fonts
[ ! -d ~/.local/share/gnome-shell/extensions ] && mkdir -p ~/.local/share/gnome-shell/extensions

#ls

echo -e "${GREEN}Copying Cursor Files${NC}"
cp -r Cursor/* ~/.icons/
echo -e "${GREEN}Copying Icon Files${NC}"
cp -r Icons/* ~/.icons/
echo -e "${GREEN}Copying Shell Files${NC}"
cp -r Shell/* ~/.themes/
echo -e "${GREEN}Copying Theme Files${NC}"
cp -r Themes/* ~/.themes/
#cp -r Apple-Darwin-For-Plymouth/darwin/* ~/Downloads/Apple-Darwin-For-Plymouth/darwin/
echo -e "${GREEN}Copying Fonts${NC}"
cp -r Fonts/* ~/.local/share/fonts/
echo -e "${GREEN}Copying Wallpapers${NC}"
cp -r Wallpapers/* ~/Pictures/

#Install the required gnome extensions
cd ~/Downloads/CustomizedPack/
echo -e "${CYAN}Starting  : ${NC}${YELLOW}Installing required extensions${NC}"
#./gnome-ext-install.sh install user-theme@gnome-shell-extensions.gcampax.github.com dash-to-dock@micxgx.gmail.com blyr@yozoon.dev.gmail.com netspeed@hedayaty.gmail.com
./gnome-ext-install.sh install blyr@yozoon.dev.gmail.com netspeed@hedayaty.gmail.com
clear
echo -e "${GREEN}Finished  : ${NC}${YELLOW}Blyr, Net Speed Monitor extensions are installed.${NC}"

#Changing UI
## Application Theme
echo -e "${BLUE}Changing Theme${NC}" 
dconf write /org/gnome/desktop/interface/gtk-theme "'macOS-5.2'" 

## Cursor
echo -e "${BLUE}Changing Cursor${NC}"
dconf write /org/gnome/desktop/interface/cursor-theme "'macOS Cursor Set'"

## Icons
echo -e "${BLUE}Changing Icons${NC}"
dconf write /org/gnome/desktop/interface/icon-theme "'Os-Catalina-icons'" 

## Shell
echo -e "${BLUE}Changing Shell${NC}"
dconf write /org/gnome/shell/extensions/user-theme/name "'macOS-5.2'"  

## Wallpaper
echo -e "${BLUE}Changing Wallpaper${NC}"
if [ $USER = "root" ]
then	
dconf write /org/gnome/desktop/background/picture-uri "'file:///root/AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0/10-15-3-Day-Sunny.jpg'"
else	dconf write /org/gnome/desktop/screensaver/picture-uri "'file:///home/$USER/AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0/10-15-5-Afternoon.jpg'" 
fi
dconf write /org/gnome/desktop/screensaver/picture-options "'zoom'"

## Show Desktop Icons
echo -e "${BLUE}Enabling Desktop Icons${NC}"
dconf write /org/gnome/desktop/background/show-desktop-icons "true"

## Button Layout
echo -e "${BLUE}Moving Title Buttons to Left${NC}"
dconf write /org/gnome/desktop/wm/preferences/button-layout "'close,minimize,maximize:'"

##### Dash To Dock
## Monitor Placement
echo -e "${BLUE}Showing Dock on Primary Monitor Only${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/preferred-monitor "0"

## Dock Placement
echo -e "${BLUE}Changing Dock Position to Bottom${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/dock-position "'BOTTOM'"

## Max Icon Size
echo -e "${BLUE}Setting Max Icon Size 32${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size "32"

## Autohide
echo -e "${BLUE}Enabling Dock Autohide${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/dock-fixed "false"

## Show Launcher on Left
echo -e "${BLUE}Showing App Launcher on Left${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-apps-at-top "true"

## Mouse Scroll Action
echo -e "${BLUE}Changing Mouse Scroll Action to Cycle Windows${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/scroll-action "'cycle-windows'"

## Custom Dock Indicator
echo -e "${BLUE}Changing Dock Indicator${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-customize-running-dots "false"

## Disable Custom Dock Shrink
echo -e "${BLUE}Disabling Custom Dock Shrink${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink "false"

## Dock Transparency Mode
echo -e "${BLUE}Changing Dock Transparency Mode${NC}"
dconf write /org/gnome/shell/extensions/dash-to-dock/transparency-mode "'DEFAULT'" 




#echo -e "${YELLOW}Uninstalling Ubuntu Dock (It might be seen on lock screen)${NC}"
#xterm -e 'sh -c "echo Ubuntu dock will be uninstalled. Please enter your password.; sudo apt-get remove gnome-shell-extension-ubuntu-dock; sudo apt update"' 

sudo add-apt-repository ppa:nilarimogard/webupd8 
sudo apt-get update 
sudo apt-get install albert 

cd ~/Downloads/AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0/Plmouth 
sudo mv darwin /usr/share/plymouth 
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/darwin/darwin.plymouth 100 
sudo update-alternatives --config default.plymouth 
sudo update-initramfs -u 

cd ~/Downloads/AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0/GDM/High_Ubunterra_DD-2.4(Pass) 
chomd +x install.sh 
./install.sh 

sudo snap remove gnome-system-monitor
sudo snap remove gnome-calculator 
sudo apt install gnome-system-monitor gnome-calculator

echo -e "${RED}Removing Downloaded Unnecessary Files${NC}" 
cd ~/Downloads/ 
rm -rf AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0 
rm AAAHuvvmLlA9xQQ_JWtl6otqa?dl=0 

echo -e "${CYAN}BY Robert Grubecki 
echo -e "${GREEN}DONE. ENJOY ;)${NC}"





